### ISSUE TITLE
Error on provision

### ISSUE THREAD

**Issue by kucrut** [Chassis/xhprof#18]
1. What operating system do you use?
Arch Linux

2. What version of Vagrant are you running?
2.2.6

3. Are you using VirtualBox or VMWare and which version are you using?
VirtualBox 6.0.14 r132055

4. Do you have a custom YAML file? If so, what does it contain?
```
php: '7.2'
paths:
  base: ..
  wp: wordpress
  content: content
multisite: true
extensions:
  - humanmade/platform_chassis_extension
elasticsearch:
  repo_version: 6.x
  version: 6.3.1
  plugins: [analysis-icu, ingest-attachment]
hosts:
  - myhost.local
machine_name: myhost.local
```
5. Do you have any Chassis other extensions installed? If so, what are they?
* cavalcade
* chassis_aws_analytics
* chassis_elasticsearch
* chassis_openssl
* chassis_redis
* composer
* example
* imagick
* intl
* mailhog
* mcrypt
* nodejs
* phpdbg
* platform_chassis_extension
* tachyon
* v8js
* xhprof
* yarn

Here's the error I got when the box is provisioned for the first time:

```
myhost.local: Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/php/7.2/fpm/conf.d/xhprof.ini20191219-2564-ycp053.lock (file: /vagrant/extensions/xhprof/modules/xhprof/manifests/init.pp, line: 52)
myhost.local: Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/php/7.2/fpm/conf.d/xhprof.ini20191219-2564-ycp053.lock (file: /vagrant/extensions/xhprof/modules/xhprof/manifests/init.pp, line: 52)
myhost.local: Wrapped exception:
myhost.local: No such file or directory @ dir_s_mkdir - /etc/php/7.2/fpm/conf.d/xhprof.ini20191219-2564-ycp053.lock
myhost.local: Error: /Stage[main]/Xhprof/File[/etc/php/7.2/fpm/conf.d/xhprof.ini]/ensure: change from 'absent' to 'file' failed: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /etc/php/7.2/fpm/conf.d/xhprof.ini20191219-2564-ycp053.lock (file: /vagrant/extensions/xhprof/modules/xhprof/manifests/init.pp, line: 52)
```

Running `vagrant provision` after the box is setup fixes the issue.
